### ISSUE TITLE
Some variable (like @No_t*) was automatically inserted during the translation.

### ISSUE THREAD

**Issue by yoshioterada** [MicrosoftDocs/windowsserverdocs.ja-jp#55]
[フィードバックをこちらに入力してください]

There is many miss translation in this documents.
In fact, some variable (like @No_t*) was automatically inserted in it during the translation like follows.

```
Copy the Install-WindowsAdminCenterHA.ps1 script to a node in your cluster. Download or copy the Windows Admin Center .msi to the same node.
@No__t-0 スクリプトをクラスター内のノードにコピーします。 Windows 管理センターの .msi をダウンロードするか、同じノードにコピーします。
```

```
-clientAccessPoint: choose a name that you will use to access Windows Admin Center. For example, if you run the script with the parameter -clientAccessPoint contosoWindowsAdminCenter, you will access the Windows Admin Center service by visiting
-clientAccessPoint: Windows 管理センターへのアクセスに使用する名前を選択します。 たとえば、-clientAccessPoint contosoWindowsAdminCenter というパラメーターを指定してスクリプトを実行した場合、@no__t にアクセスして Windows 管理センターサービスにアクセスします。
```

```
-certPassword: Optional. A SecureString password for the certificate .pfx provided in -certPath
-certPassword:任意。 @No__t-0 で提供されている証明書の SecureString パスワード
```
Additonal Note: in this place, .pfx was not include in the translated documents.

```
-portNumber: Optional. If you don't specify a port, the gateway service is deployed on port 443 (HTTPS). To use a different port specify in this parameter. Note that if you use a custom port (anything besides 443), you'll access the Windows Admin Center by going to https://<clientAccessPoint>:<port>.
-portNumber:任意。 ポートを指定しない場合、ゲートウェイサービスはポート 443 (HTTPS) に展開されます。 別のポートを使用するには、このパラメーターにを指定します。 カスタムポート (443 を除く) を使用する場合は、 https://<clientAccessPoint @ no__t-1: <port @ no__t-3 に移動して、Windows 管理センターにアクセスします。
```

```
The Install-WindowsAdminCenterHA.ps1 script supports -WhatIf and -Verbose parameters
@No__t-0 スクリプトでは、-WhatIf と -Verbose のパラメーターがサポートされています。
```

```
Update an existing high availability installation
Use the same Install-WindowsAdminCenterHA.ps1 script to update your HA deployment, without losing your connection data.
既存の高可用性インストールを更新する
同じ @no__t 0 スクリプトを使用して、接続データを失うことなく、HA デプロイを更新します。
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 32deb7a0-4ea0-caf1-0777-580539173e44
* Version Independent ID: a6ee1f9d-b316-c69d-fa9d-2a1556454868
* Content: [高可用性を備えた Windows 管理センターの展開](https://docs.microsoft.com/ja-jp/windows-server/manage/windows-admin-center/deploy/high-availability?fbclid=IwAR1o4RF4nFbYCBWXrR7rbly9N0Oe8aTz3JFBQl1q4N_bn-vGs-yHOfPRHWE)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md](https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/blob/live/WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by srvbpigh** [comment]
Hello, @yoshioterada
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yoshioterada

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/windows-server/manage/windows-admin-center/deploy/high-availability

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
