### ISSUE TITLE
パラメータが変に日本語訳されてしまっている

### ISSUE THREAD

**Issue by xyzpda** [MicrosoftDocs/windowsserverdocs.ja-jp#57]
誤　→　/除外:
正　→　/exclude:

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 544925b9-8587-3e0e-9d49-44b77dbd290d
* Version Independent ID: e9969211-1085-ca1f-afb5-b619edbbfab3
* Content: [xcopy](https://docs.microsoft.com/ja-jp/windows-server/administration/windows-commands/xcopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/blob/live/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @xyzpda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@xyzpda   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/windows-server/administration/windows-commands/xcopy#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
