### ISSUE TITLE
RDP parameter names are translated

### ISSUE THREAD

**Issue by taiyaki32lp64** [MicrosoftDocs/windowsserverdocs.ja-jp#68]
RDP parameter names are translated incorrectly (maybe by machine translation?). They should not be translated.

English: "Disable wallpaper:i:0"
Actual: "壁紙を無効にする: i: 0"
Expected: "Disable wallpaper:i:0"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1464c085-bd3e-2203-9db7-b5859d47869f
* Version Independent ID: b8798918-a626-9c6a-197e-a48ba9690ee7
* Content: [リモートデスクトップセッションホストのパフォーマンスチューニング](https://docs.microsoft.com/ja-jp/windows-server/administration/performance-tuning/role/remote-desktop/session-hosts)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/remote-desktop/session-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/blob/live/WindowsServerDocs/administration/performance-tuning/role/remote-desktop/session-hosts.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @phstee
* Microsoft Alias: **hammadbu; vladmis; denisgun**

**Comment by srvbpigh** [comment]
Hello, @taiyaki32lp64
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @taiyaki32lp64 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
