### ISSUE TITLE
”この内容のセクション” の訳が間違えています。

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/windowsserverdocs.ja-jp#69]
このセクションの内容
RHEL/CentOS 8. x シリーズ
★ RHEL/CentOS 6.x シリーズ  → 7.x シリーズの間違いだと思います。
RHEL/CentOS 6.x シリーズ
RHEL/CentOS 5.x シリーズ
メモ

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 988640af-813f-0ca3-8844-b09cf359f9cf
* Version Independent ID: 8be01cd9-2034-f44d-1016-3af62b7f0e15
* Content: [CentOS をサポートし、HYPER-V 上の Red Hat Enterprise Linux 仮想マシン](https://docs.microsoft.com/ja-jp/windows-server/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/blob/live/WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **vichen**

**Comment by srvbpigh** [comment]
Hello, @mattu0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@mattu0119  様:  

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 


サポートいただきありがとうございます。 


Microsoft DOCS グローバル エクスペリエンス チーム
