### ISSUE TITLE
[Trasn Bug]: left side of the menu is not translated correctly.

### ISSUE THREAD

**Issue by yoshioterada** [MicrosoftDocs/windowsserverdocs.ja-jp#71]
Left side of the menu is not translated correctly.
The original was "Use" however the translated document was wrote as "vmmblue_2".
--------------------
- 構成
- vmmblue_2  &lt;---- this is the point of the issue. It should be translated as "利用" , "動作確認"
  + 作業開始
  + サーバの管理
  + ハイパーコンバージどインフラストラクチャの展開
--------------------
- Configure
- Use  &lt;-------- This is the point 
  + Get Started
  + Manage Servers
--------------------

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6eeacf83-f081-d3ac-2d08-60bf6acde0a4
* Version Independent ID: 20153ee2-be3c-5a77-3fba-0b5bfe763bec
* Content: [Windows 管理センターの使用を開始する](https://docs.microsoft.com/ja-jp/windows-server/manage/windows-admin-center/use/get-started?fbclid=IwAR1-LVkgxyJjY94XhfjCPYanX7IdJcV75iCsuHIb81lA4IMslgYVBLeqAvU#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs.ja-jp/blob/live/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by srvbpigh** [comment]
Hello, @yoshioterada
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @yoshioterada 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
